// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import * as ph from "@plasmicapp/host";

import { ScreenVariantProvider } from "../components/plasmic/ratisbona_coding_e_v/PlasmicGlobalVariant__Screen";
import { PlasmicAbout } from "../components/plasmic/ratisbona_coding_e_v/PlasmicAbout";
import { useRouter } from "next/router";

function About() {

  return (
    //<ph.PageParamsProvider params={useRouter().query} query={useRouter().query}>
      <PlasmicAbout />
    //</ph.PageParamsProvider>
  );
}

export default About;
